name: Discord Notification

on:
  pull_request:
    types: [ closed ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract frontmatter
        id: frontmatter
        run: |
          LATEST_FILE=$(ls -t blog/*.md | head -n1)
          TITLE=$(grep "title:" "$LATEST_FILE" | cut -d '"' -f 2)
          SUMMARY=$(grep "summary:" "$LATEST_FILE" | cut -d ':' -f 2- | xargs)
          echo "title=$TITLE" >> $GITHUB_ENV
          echo "summary=$SUMMARY" >> $GITHUB_ENV

      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -d '{
           "embeds": [{
              "title": "✨ Nouvel article publié",
              "description": "${{ env.title }}",
              "color": 5814783,
              "fields": [
                {
                  "name": "📝 Résumé",
                  "value": "${{ env.summary }}"
                },
                {
                  "name": "🌐 Site web",
                  "value": "http://codechronicle-hugo-potier.fwh.is/"
                }
              ],
              "footer": {
                "text": "CodeChronicle"
              }
            }]
          }'